# Generated by Django 4.2.7 on 2023-11-24 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('phoneNo', models.CharField()),
                ('addressDetails', models.JSONField()),
                ('hno', models.CharField()),
                ('street', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('workExperience', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('companyName', models.CharField()),
                ('fromDate', models.CharField()),
                ('toDate', models.CharField()),
                ('address', models.CharField()),
                ('qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('qualificationName', models.CharField()),
                ('percentage', models.FloatField()),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('title', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
