# Generated by Django 4.2.7 on 2023-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_city_remove_employee_hno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualificationName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='toDate',
        ),
    ]
